repos:
  - name: rEFInd
    origin:
      url: https://git.code.sf.net/p/refind/code
    target:
      url: git@github.com:mix-mirror/rEFInd.git
      auth: &auth
        type: ssh
        ssh_private_key: ${SSH_PRIVATE_KEY}

  - name: cado-nfs
    origin:
      url: https://gitlab.inria.fr/cado-nfs/cado-nfs.git
    target:
      url: git@github.com:mix-mirror/cado-nfs.git
      auth: *auth

  - name: mmc-utils
    origin:
      url: https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git
    target:
      url: git@github.com:mix-mirror/mmc-utils.git
      auth: *auth

  - name: BusyBox
    origin:
      url: git://busybox.net/busybox.git
    target:
      url: git@github.com:mix-mirror/busybox.git
      auth: *auth

  - name: libinput
    origin:
      url: https://gitlab.freedesktop.org/libinput/libinput.git
    target:
      url: git@github.com:mix-mirror/libinput.git
      auth: *auth

  - name: ocserv
    origin:
      url: https://gitlab.com/openconnect/ocserv.git
    target:
      url: git@github.com:mix-mirror/ocserv.git
      auth: *auth
